### ISSUE TITLE
Geojson data for algerian wilayas boundaries (58 wilayas)

### ISSUE THREAD

**Issue by iladan0** [fr33dz/Algeria-geojson#1]
https://github.com/iladan0/Wilayas-Algeria
i hope this is useful for you guys 
i used it to make simple interactive map showing population density(2008) per wilaya
https://github.com/iladan0/Algerian-Population-Density

if you like my work plz give it a star ^^

**Comment by fr33dz** [comment]
merci pour la contribution ;)

**Comment by oussamallali** [comment]
HI I would like to thank you for your sharing GeoJSON wilaya contours, you saved me lots of time and effort

**Comment by touagueni** [comment]
Thanks for sharing!
